name: refilc_plus
publish_to: "none"

environment:
  sdk: ">=2.17.0 <=3.3.2"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # reFilc Main
  refilc:
    path: ../refilc/
  # e-KRETA API (kreten) client
  refilc_kreta_api:
    path: ../refilc_kreta_api/
  # reFilc Mobile UI
  refilc_mobile_ui:
    path: "../refilc_mobile_ui/"

  provider: ^6.1.1
  flutter_feather_icons: ^2.0.0+1
  uni_links: ^0.5.1
  url_launcher: ^6.2.5
  dropdown_button2: ^2.3.9
  home_widget: ^0.4.1
  image_picker: ^1.0.7
  image_crop:
    git:
      url: https://github.com/kimaah/image_crop.git
  lottie: ^3.1.0
  animations: ^2.0.11
  flutter_svg: ^2.0.10+1
  flutter_dynamic_icon: ^2.1.0
  android_dynamic_icon: ^1.0.1
  i18n_extension: ^11.0.12
  http: ^1.2.0
  fl_chart: ^0.45.1
  flutter_dynamic_icon_plus: ^1.1.2
  share_plus: ^7.2.2
  path_provider: ^2.1.3
  file_picker: ^6.2.1

dev_dependencies:
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
